(defun menorQue(E L)
    (cond ((null L) ())
          ( (< (car L) E) (cons (car L) (menorQue E (cdr L))) )
          (t (menorQue E (cdr L)))
    )
)

(defun maiorQue(E L)
    (cond ((null L) ())
          ( (>= (car L) E) (cons (car L) (maiorQue E (cdr L))) )
          (t (maiorQue E (cdr L)))
    )
)

(defun ordenaRapido(L)
    (cond ((<= (length L) 1) L)
          (t (append (ordenaRapido (menorQue (car L) (cdr L))) (cons (car L) (ordenaRapido (maiorQue (car L) (cdr L))))) )
    )
)
